config/routes.rb
Rails.application.routes.draw do
  scope :api do
    resources :tw_users
    resources :papers
  end
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  serialize :tags, Array

  validates :url, uniqueness: true, presence: true
  validates :title, presence: true
  validates :text, presence: true

  def self.new_from_url url
    data = Unfluffer::unfluff url
    
    data.slice!(:title, :text, :image, :videos, :tags, :lang, :description,
                :favicon, :url)

    data[:tags] = data[:tags].map do |t|
      t.strip
    end

    new data
  end
end

app/models/tw_user.rb
class TwUser < ActiveRecord::Base
  validates :screen_name, presence: true, uniqueness: true
  validates :name, presence: true
  validates :description, presence: true
  validates :profile_image_url, presence: true

  def self.new_from_screen_name screen_name
    twitter_user = TwClient.user(screen_name)

    new screen_name: twitter_user.screen_name,
        name: twitter_user.name,
        description: twitter_user.description,
        profile_image_url: twitter_user.profile_image_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.order(id: :desc).limit(100)
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:title, :text, :image, :videos, :tags, :lang, :description, :favicon, :url)
    end
end

app/controllers/tw_users_controller.rb
class TwUsersController < ApplicationController
  before_action :set_tw_user, only: [:show, :edit, :update, :destroy]

  # GET /tw_users
  # GET /tw_users.json
  def index
    @tw_users = TwUser.all
  end

  # GET /tw_users/1
  # GET /tw_users/1.json
  def show
  end

  # GET /tw_users/new
  def new
    @tw_user = TwUser.new
  end

  # GET /tw_users/1/edit
  def edit
  end

  # POST /tw_users
  # POST /tw_users.json
  def create
    @tw_user = TwUser.new(tw_user_params)

    respond_to do |format|
      if @tw_user.save
        format.html { redirect_to @tw_user, notice: 'Twitter user was successfully created.' }
        format.json { render :show, status: :created, location: @tw_user }
      else
        format.html { render :new }
        format.json { render json: @tw_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tw_users/1
  # PATCH/PUT /tw_users/1.json
  def update
    respond_to do |format|
      if @tw_user.update(tw_user_params)
        format.html { redirect_to @tw_user, notice: 'Twitter user was successfully updated.' }
        format.json { render :show, status: :ok, location: @tw_user }
      else
        format.html { render :edit }
        format.json { render json: @tw_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tw_users/1
  # DELETE /tw_users/1.json
  def destroy
    @tw_user.destroy
    respond_to do |format|
      format.html { redirect_to tw_users_url, notice: 'Twitter user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tw_user
      @tw_user = TwUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tw_user_params
      params.require(:tw_user).permit(:screen_name, :name, :description, :profile_image_url, :profile_image_url_https)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/tw_users_helper.rb
module TwUsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uatu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :videos %><br>
    <%= f.text_area :videos %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_area :tags %>
  </div>
  <div class="field">
    <%= f.label :lang %><br>
    <%= f.text_field :lang %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :favicon %><br>
    <%= f.text_area :favicon %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Papers</h1>

<% @papers.each do |paper| %>
    <p>
      <%= paper.title %>
    </p>
    <p><%= paper.text.gsub(/\n/, '<br/>').html_safe %></p>
    <p><%= paper.image %></p>
    <p><%= paper.videos %></p>
    <p><%= paper.tags %></p>
    <p><%= paper.lang %></p>
    <p>
      <%= paper.description %>
    </p>
    <p><%= paper.favicon %></p>
    <p><%= paper.url %></p>
    <p><%= link_to 'Show', paper %></p>
    <p><%= link_to 'Edit', edit_paper_path(paper) %></p>
    <p><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

<br>

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @paper.text %>
</p>

<p>
  <strong>Image:</strong>
  <%= @paper.image %>
</p>

<p>
  <strong>Videos:</strong>
  <%= @paper.videos %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @paper.tags %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @paper.lang %>
</p>

<p>
  <strong>description:</strong>
  <%= @paper.description %>
</p>

<p>
  <strong>Favicon:</strong>
  <%= @paper.favicon %>
</p>

<p>
  <strong>Url:</strong>
  <%= @paper.url %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>

app/views/tw_users/_form.html.erb
<%= form_for(@tw_user) do |f| %>
  <% if @tw_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tw_user.errors.count, "error") %> prohibited this tw_user from being saved:</h2>

      <ul>
      <% @tw_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :screen_name %><br>
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :profile_image_url %><br>
    <%= f.text_field :profile_image_url %>
  </div>
  <div class="field">
    <%= f.label :profile_image_url_https %><br>
    <%= f.text_field :profile_image_url_https %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tw_users/edit.html.erb
<h1>Editing Twitter User</h1>

<%= render 'form' %>

<%= link_to 'Show', @tw_user %> |
<%= link_to 'Back', tw_users_path %>

app/views/tw_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Twitter Users</h1>

<table>
  <thead>
    <tr>
      <th>Screen name</th>
      <th>Name</th>
      <th>Description</th>
      <th>Profile image url</th>
      <th>Profile image url https</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tw_users.each do |tw_user| %>
      <tr>
        <td><%= tw_user.screen_name %></td>
        <td><%= tw_user.name %></td>
        <td><%= tw_user.description %></td>
        <td><%= tw_user.profile_image_url %></td>
        <td><%= tw_user.profile_image_url_https %></td>
        <td><%= link_to 'Show', tw_user %></td>
        <td><%= link_to 'Edit', edit_tw_user_path(tw_user) %></td>
        <td><%= link_to 'Destroy', tw_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twitter user', new_tw_user_path %>

app/views/tw_users/new.html.erb
<h1>New Twitter User</h1>

<%= render 'form' %>

<%= link_to 'Back', tw_users_path %>

app/views/tw_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Screen name:</strong>
  <%= @tw_user.screen_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tw_user.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tw_user.description %>
</p>

<p>
  <strong>Profile image url:</strong>
  <%= @tw_user.profile_image_url %>
</p>

<p>
  <strong>Profile image url https:</strong>
  <%= @tw_user.profile_image_url_https %>
</p>

<%= link_to 'Edit', edit_tw_user_path(@tw_user) %> |
<%= link_to 'Back', tw_users_path %>

app/views/twitter_users/_form.html.erb
<%= form_for(@twitter_user) do |f| %>
  <% if @twitter_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter_user.errors.count, "error") %> prohibited this twitter_user from being saved:</h2>

      <ul>
      <% @twitter_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :screen_name %><br>
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :profile_image_url %><br>
    <%= f.text_field :profile_image_url %>
  </div>
  <div class="field">
    <%= f.label :profile_image_url_https %><br>
    <%= f.text_field :profile_image_url_https %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_users/new.html.erb
<h1>New Twitter User</h1>

<%= render 'form' %>

<%= link_to 'Back', twitter_users_path %>